---
# Tasks for mysql role

- name: install mysql packages
  yum: name={{ item }} state=installed
  with_items:
    - mysql-server
    - mysql

- name: start mysql services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - mysqld

- name: set mysql root passwd
  command: /usr/bin/mysqladmin -u root password {{ mysql_root_pass }}

- name: set mysql root my.cnf
  template: src=my.cnf.j2 dest=/root/.my.cnf
